# Generated by Django 5.1 on 2024-10-15 16:07

import tiendaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_alter_empleado_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='empleados/empleado.png', null=True, upload_to=tiendaApp.models.Empleado.generarNombre),
        ),
    ]
