# Generated by Django 5.1.1 on 2024-11-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
    ]
