# Generated by Django 5.1.2 on 2024-11-04 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0007_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='codigoEmpleado',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(default='Sin tipo', max_length=50),
        ),
    ]
