# Generated by Django 5.1.2 on 2024-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0008_solicitud_codigoempleado_solicitud_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigoEmpleado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
