# Generated by Django 5.1.2 on 2024-11-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0009_solicitud_archivo_alter_solicitud_codigoempleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigoEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.empleado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
