# Generated by Django 5.1.1 on 2024-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
