# Generated by Django 5.1.2 on 2024-11-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_empleado_hora_entrada_empleado_hora_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('posicion_solicitada', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, default='En Proceso', max_length=50)),
            ],
        ),
    ]
